# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
# fos_rest: ~
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    routing_loader:
        default_format: json
        include_format: false
    view:
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1']
        view_response_listener: force
        formats:
            xml: false
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json, html ], fallback_format: json, prefer_extension: true }
#        media_type:
#            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
#        exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
# , attributes: { _controller: 'fos_rest.exception.twig_controller:showAction' }
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true
    
    
